# This is a basic workflow to help you get started with Actions

name: coverage-report

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      matlab:
        required: false
        type: string
        default: latest
      runner:
        required: false
        type: string
        default: ubuntu-latest
      thresholds:
        required: false
        type: string
        default: '60 90'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
    - name: Download test artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: coverage_matlab-${{matlab}}_${{runner}}
        merge-multiple: true
        path: coverage
        
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/*.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: true
        hide_complexity: true
        indicators: false
        output: both
        thresholds: ${{ thresholds }}
    
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
